version: '3.8'
services:

  faiss:
    build: ./faiss
    volumes:
      - ./sample_docs:/data/sample_docs
    ports:
      - "19530:19530"

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - faiss
